### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by jtbales** [polygon-io/client-js#24]
Please provide better error handling. 

I made a simple mistake, I put a date as '2020-1-1' instead of '2020-01-01'. 

But the error I receive is 

```
(node:30158) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at Object.exports.formatIAggResponseRaw (/Users/jbales/Personal-Repos/market-mind-js/node_modules/polygon.io/lib/rest/stocks/aggregates.js:14:104)
    at /Users/jbales/Personal-Repos/market-mind-js/node_modules/polygon.io/lib/rest/stocks/aggregates.js:21:20
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jbales/Personal-Repos/market-mind-js/node_modules/polygon.io/lib/rest/stocks/aggregates.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:30158) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30158) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is hardly helpful. 

I had to go to the source code and change it to this 
```
exports.formatIAggResponseRaw = (raw) => {
    console.log('raw', raw);
    return (Object.assign(Object.assign({}, raw), { results: raw.results.map(formatIAggv2Raw) }))
};
```

Only then I could see that the error was 
```
raw {
  status: 'ERROR',
  request_id: '6e801099337ce7a767a9e03041aca080',
  error: "Could not parse the time parameter: 'from'. Use YYYY-MM-DD or Unix MS Timestamps"
}
```

We shouldn't have to dig into source code to discover errors, large or small. 

Please incorporate error handling propagation in all your calls so error messages are clear and helpful.

**Comment by teambailey** [comment]
Thank you for your feedback and interest in our service! The latest release, [v4.0.2](https://github.com/polygon-io/client-js/releases/tag/v4.0.2), should address this issue.
