### ISSUE TITLE
Internal error is surfaced when no data is available

### ISSUE THREAD

**Issue by jdgriffith** [polygon-io/client-js#41]
```
[Nest] 3177   - 05/15/2021, 10:28:47 AM   Cannot read property 'map' of undefined +43ms
TypeError: Cannot read property 'map' of undefined
    at Object.formatIAggResponseRaw (/Users/justingriffith/Workspaces/trading-algorithms/node_modules/polygon.io/lib/rest/stocks/aggregates.js:15:102)
    at /Users/justingriffith/Workspaces/trading-algorithms/node_modules/polygon.io/lib/rest/crypto/aggregates.js:22:25
    at Generator.next (<anonymous>)
    at fulfilled (/Users/justingriffith/Workspaces/trading-algorithms/node_modules/polygon.io/lib/rest/crypto/aggregates.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

When using your client I would expect to either receive a different error or merely get back an empty result set. This kind of thing should be handled internally within your library in practice.

**Comment by jdgriffith** [comment]
I can maybe submit a PR for this if that would help.

**Comment by sakekasi** [comment]
+1, I'm running into this issue as well. It'd be nice if this error was more descriptive, so I knew it was coming from polygon

**Comment by teambailey** [comment]
Hi @jdgriffith - Thank you for your interest in Polygon.io! Formatting the response is not a practice we're moving forward with in the JS client. The latest release, [v4.0.2](https://github.com/polygon-io/client-js/releases/tag/v4.0.2), should not have the same issues.
